# https://travis-ci.org/jf3096/test-travis

# 使用 nodejs
language: node_js

git:
  depth: 1

before_install:
  - |
    if [[ $TRAVIS_COMMIT_MESSAGE != "release:"* ]]
    then
      echo "commit message 中没有使用 ‘release:’ 开头故终止当前 CI."
      exit
    fi

script:
  - yarn start

branches:
  only:
    - gh-pages
    - /.*/
  except:
    - master
    - template
    - - /^test-.*$/

jobs:
  include:
    - stage: deploy
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true
        edge: true
